#!/bin/bash

if [ ! -f "vendor/autoload.php" ]; then
    composer install --no-progress --no-interaction
fi

if [ ! -f ".env" ]; then
    echo "Creating env file for env $APP_ENV"
    cp .env.example .env
fi

role=${CONTAINER_ROLE: -app}

if [ "$role" == "app" ]; then
    echo "Configuring the app ...."
    php artisan key:generate
    php artisan optimize:clear
    php artisan storage:link
    php artisan migrate
    php artisan serve --port="$APP_PORT" --host=0.0.0.0 --env=.env
    exec docker-php-entrypoint "$@"
elif [ "$role" == "queue" ]; then
    echo "Running the queue ...."
    php /var/www/html/artisan queue:work --verbose --tries=3 --timeout=180

fi


